### ISSUE TITLE
I can't install itermocil. 

### ISSUE THREAD

**Issue by hanakang** [TomAnthony/homebrew-brews#4] opened 2021-10-12 06:13 UTC
Hi. Thank you for your tool. 
But I can't install itermocil by homebrew.

```
$ brew install TomAnthony/brews/itermocil
==> Tapping tomanthony/brews
Cloning into '/usr/local/Homebrew/Library/Taps/tomanthony/homebrew-brews'...
remote: Enumerating objects: 77, done.
remote: Total 77 (delta 0), reused 0 (delta 0), pack-reused 77
Unpacking objects: 100% (77/77), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/tomanthony/homebrew-brews/Formula/squid.rb
squid: Calling `sha256 "digest" => :tag` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the tomanthony/brews tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/tomanthony/homebrew-brews/Formula/squid.rb:9

Error: Cannot tap tomanthony/brews: invalid syntax in tap!
```

please help me. 

<img width="260" alt="스크린샷 2021-10-12 오후 3 14 19" src="https://user-images.githubusercontent.com/18586561/136901562-dc19f412-7f80-4a9f-b71f-efca264e46e4.png">

**Comment by ksingh7** [comment] 2022-03-21 22:00
Facing same error , need help

**Comment by th3N0m4d** [comment] 2022-03-23 11:34
Possible duplicate of [this](https://github.com/TomAnthony/itermocil/issues/119) another issue.

**Comment by ruudk** [comment] 2022-04-09 13:17
The problem has been fixed in https://github.com/TomAnthony/itermocil, please run `brew update && brew install tomanthony/brews/itermocil` to retry.

**Closed as completed by ruudk** 2022-04-09 13:17 UTC
